---
title: "World Cup 2018"
knit: (function(inputFile, encoding) { 
  out_dir <- "docs";
  rmarkdown::render(inputFile,
                      encoding=encoding, 
                      output_file=file.path(dirname(inputFile), out_dir, 'index.html'))})
output:
  html_document:
    df_print: paged
---


```{r, include = FALSE}
library(rvest)
library(readr)
library(tidyverse)
library(plotly)
library(DT)
library(countrycode)
```



```{r, include = FALSE}
elo_ratings_tab <- read_tsv("http://www.eloratings.net/World.tsv", col_names = FALSE)
elo_ratings_tab <- elo_ratings_tab %>%   
  select(X3, X4) %>% 
  rename(country_iso = X3, "score" = X4) %>% 
  mutate(country = countrycode(country_iso, "iso2c", "country.name"),
         country = if_else(country_iso == "EN", "England", country),
         country = if_else(country_iso == "WA", "WALES", country),
         country = if_else(country_iso == "AA", "Scotland", country),
         country = if_else(country_iso == "EI", "Northern Ireland", country),
         country = if_else(country_iso == "RU", "Russia", country),
         country = if_else(country_iso == "IR", "Iran", country),
         country = if_else(country_iso == "KR", "South Korea", country)) %>% 
  select(-country_iso)
  
```


```{r, include = FALSE}
schedule_web <- read_html("http://www.independent.co.uk/sport/football/world-cup/world-cup-2018-full-schedule-groups-fixtures-kick-off-times-venues-matches-wallchart-a8087881.html")


schedule_tab <- html_table(schedule_web, fill = TRUE)[[1]] %>% 
  slice(3:50) %>% 
  select(X2) %>% 
  separate(X2, c("home", "away"), sep = " v ") %>% 
  separate(away, c("away", "group"), sep = " \\(") %>% 
  mutate(group = factor(str_sub(group, end = 1)))
```


```{r, include = FALSE}
schedule_prob <- schedule_tab %>% 
  left_join(elo_ratings_tab, by = c("home" = "country")) %>% 
  left_join(elo_ratings_tab, by = c("away" = "country"), suffix = c("_home", "_away"))  %>% 
  mutate(diff = score_home - score_away,
    win_home = 1/(10^(-diff/400)+1),
    win_away = 1- win_home)
```

## All Matches

```{r, echo =FALSE}
schedule_prob %>% 
  arrange(group) %>% 
  datatable(filter = "top", options = list(pageLength = 12)) %>% 
  formatStyle(c(7,8) ,background = styleColorBar(0:1, 'lightblue')) %>% 
  formatPercentage(c(7,8), digits = 2)
```

## Group with the strongest Teams

```{r, echo =FALSE}
schedule_prob %>% 
  group_by(home, group) %>% 
  summarise() %>% 
  left_join(elo_ratings_tab, by = c("home" = "country")) %>% 
  group_by(group) %>% 
  summarise(score = sum(score)) %>% 
  arrange(desc(score)) %>% 
  mutate(group = fct_reorder(group, score)) %>% 
plot_ly( type="bar", x = ~group, y = ~score)

```

## Simulated group results

```{r, include = FALSE}

sim_group_stage <- function(df, n){

group_sim <- list()
  
for (i in 1:n){
  
group_stage <- df %>% 
  mutate(result_sim = runif(n()),
         winner = if_else(result_sim <= win_home, home, away),
         diff_winner = if_else(result_sim <= win_home, win_home - result_sim , -(win_home - result_sim)),
         diff_home = if_else(result_sim <= win_home, diff_winner, -diff_winner),
         diff_away = if_else(result_sim <= win_home, -diff_winner, diff_winner),
         home_winner = if_else(diff_home > 0, 1, 0 ),
         away_winner = if_else(diff_away > 0, 1, 0 ))


table_group <- group_stage %>% 
  gather(key = "key", value= "team", home, away) %>%
  mutate(win = if_else(key == "home", home_winner, away_winner),
         diff_goal = if_else(key == "home", diff_home, diff_away)) %>% 
  group_by(group, team) %>% 
    summarise(points = sum(win)*3,
              goal_diff = sum(diff_goal)) %>% 
  arrange(group, desc(points), desc(goal_diff)) %>% 
  ungroup() %>% 
  add_column(sim = i, group_rank = rep(1:4,8))

group_sim[[i]] <- table_group


}
group_sim
}

```


## Qualified for Quarter Finals

```{r, echo = FALSE}
#group_stage_simulated <- sim_group_stage(schedule_prob, 10000)

# saveRDS(group_stage_simulated, "group_stage_simulated.rds")

group_stage_simulated <- readRDS("group_stage_simulated.rds")

qualified <- bind_rows(group_stage_simulated) %>% filter(group_rank %in% c(1,2)) %>% 
  group_by(group, team) %>% 
  summarise(next_stage = n() / length(group_stage_simulated)) %>% 
  arrange(group, desc(next_stage))

qualified %>% 
  datatable(options = list(pageLength = 8)) %>% 
  formatStyle(3 ,background = styleColorBar(0:1, 'lightblue')) %>% 
  formatPercentage(3, digits = 2)
  
  
```

## Winner of Group

```{r, echo = FALSE}
group_win <- bind_rows(group_stage_simulated) %>% filter(group_rank == 1) %>% 
  group_by(group, team) %>% 
  summarise(next_stage = n() / length(group_stage_simulated)) %>% 
  arrange(group, desc(next_stage))

group_win %>% 
  datatable(options = list(pageLength = 8)) %>% 
  formatStyle(3 ,background = styleColorBar(0:1, 'lightblue')) %>% 
  formatPercentage(3, digits = 2)
```

## Runner Up of group

```{r, echo = FALSE}
group_runner_up <- bind_rows(group_stage_simulated) %>% filter(group_rank == 2) %>% 
  group_by(group, team) %>% 
  summarise(next_stage = n() / length(group_stage_simulated)) %>% 
  arrange(group, desc(next_stage))

group_runner_up %>% 
  datatable(options = list(pageLength = 8)) %>% 
  formatStyle(3 ,background = styleColorBar(0:1, 'lightblue')) %>% 
  formatPercentage(3, digits = 2)
```

